### ISSUE TITLE
Feature request: include metadata in download

### ISSUE THREAD

**Issue by ericsfraga** [splitbrain/ReMarkableAPI#6]
I have scripts that use the metadata information to process the lines files from the tablet.  It would be very helpful if the download, using the php script, could include the metadata file along with the others in the zip file created.

**Comment by splitbrain** [comment]
The API currently returns the zip as stored on the remarkable storage servers. It does not include the metadata because that is managed via the storage API server.

We would need to create the meta file from the item info we have. That part is easy, but the used zip library does not support amending zip files on the fly currently.

Process would be to unpack the zip, generate the metafile, create a new zip with everything. It would probably be easier to just download everything into a provided directory.

How are you using my code? As a command line script or as a library?

**Comment by ericsfraga** [comment]
Thanks for the explanation.  I use your code as a command line script.

Given the above, don't worry about it. I can get what I need indirectly via your script: I'll update my scripts appropriately. It's basically the document name and folder information that I normally extract from the metadata file.

**Comment by ericsfraga** [comment]
Oh, one quick question (to avoid opening another issue): what are the first three characters on each line in the output from the "list" command?  They are not UTF-8 and simply come out as unknown glyphs for me on Linux.

**Comment by splitbrain** [comment]
They are UTF-8. Here's how it looks on my Linux system right now:

![2018-02-06-142943_566x96_scrot](https://user-images.githubusercontent.com/86426/35861993-56cdd77e-0b4a-11e8-93ad-6b1ffa37dd7e.png)

**Comment by ericsfraga** [comment]
Thanks. I must have something configured badly on my system then.
